### ISSUE TITLE
Help Menu — Translation is displayed incorrectly.

### ISSUE THREAD

**Issue by SefoNotasi** [fbef0102/L4D1_2-Plugins#42]
The help menu is displayed incorrectly with translation. For example I wrote some simple, short menu items in English and translated them into Russian. In English, everything is displayed correctly with the Back and Exit buttons:
![Help eng ok](https://github.com/fbef0102/L4D1_2-Plugins/assets/62970952/0a9ee44d-628e-4767-90c8-88a531ef3029)

But the same thing doesn't appear correctly in Russian: the last menu item is cut off in the middle of a sentence, and the Back and Exit buttons have disappeared altogether:
![Help ru broken (marked)](https://github.com/fbef0102/L4D1_2-Plugins/assets/62970952/b27a3094-5feb-4190-b6e2-d0052418f538)

There are no errors in the logs. Any ideas how to fix this, please?

**Comment by fbef0102** [comment]
Menu has character maximum limit.
This is engine limit, can not be changed

Please reduce the words when translate.

**Comment by fbef0102** [comment]
Because in computer program,  it has different size to store different language word.
For example
`English "A" takes 1 byte`
`Chinese "哈" takes 2 bytes`
I guess a Russian alphabet takes 2 bytes ?

> Do you know what the limitations are? I mean the maximum number of characters per item or menu as a whole?

The whole menu limit is 512, also there is limit for title and each options, but not sure how much (around 200).
